"""cancel

Revision ID: 46402c101320
Revises: 771ed6de6efb
Create Date: 2022-08-13 23:50:12.459076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46402c101320'
down_revision = '771ed6de6efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
