"""add new fields in user model

Revision ID: 771ed6de6efb
Revises: 8cb47fc65a65
Create Date: 2022-08-13 22:50:28.905051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771ed6de6efb'
down_revision = '8cb47fc65a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
